version: "3.1"

services:
  api:
    build:
      context: ./api
    ports:
      - 8080:4000
    depends_on:
      - database
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules/

  client:
    build:
      context: ./client
    ports:
      - 3003:3000
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules/

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8801:8080

volumes:
  database:
