version: "3.1"

services:
  api:
    build:
      context: ./api
    ports:
      - 8080:4000
    depends_on:
      - database
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules/

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=clash_of_worlds
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8801:8080

volumes:
  database:
